In [6]:
import cv2
import numpy as np
import face_recognition
import os
from datetime import datetime

In [7]:
path = 'img'
images = []
classNames = []
myList = os.listdir(path)
print(myList)

['Eslam Zoghla.jpg', 'Mohamed sabry.jpg', 'Soliman Mahmoud.jpg', 'yahya hamza.jpg']


In [8]:
for cl in myList:
    curImg = cv2.imread(f'{path}/{cl}')
    images.append(curImg)
    classNames.append(os.path.splitext(cl)[0])
print(classNames)

['Eslam Zoghla', 'Mohamed sabry', 'Soliman Mahmoud', 'yahya hamza']


In [9]:
def findEncodings(images):
    encodeList = []
    for img in images:
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        encode = face_recognition.face_encodings(img)[0]
        encodeList.append(encode)
    return encodeList

In [10]:
def markAttendance(name):
    with open('Attendance.csv','r+') as f:
        myDataList = f.readlines()
        nameList = []
        for line in myDataList:
            entry = line.split(',')
            nameList.append(entry[0])
        if name not in nameList:
            now = datetime.now()
            dtString = now.strftime('%H:%M:%S')
            f.writelines(f'\n{name},{dtString}')
        

encodeListKnown = findEncodings(images)
print('Encoding Complete')


Encoding Complete


In [12]:
cap = cv2.VideoCapture(0)
frame_resizing = 0.25

while True:
    success, img = cap.read()
    imgS = cv2.resize(img, (0, 0), fx=frame_resizing, fy=frame_resizing)
    imgS = cv2.cvtColor(imgS, cv2.COLOR_BGR2RGB)
 
    facesCurFrame = face_recognition.face_locations(imgS)
    encodesCurFrame = face_recognition.face_encodings(imgS,facesCurFrame)
 
    for encodeFace,faceLoc in zip(encodesCurFrame,facesCurFrame):
        matches = face_recognition.compare_faces(encodeListKnown,encodeFace)
        print('matches',matches)
        faceDis = face_recognition.face_distance(encodeListKnown,encodeFace)
        print(faceDis)
        matchIndex = np.argmin(faceDis)
        if matches[matchIndex]:
            name = classNames[matchIndex].upper()
            print(name)
            
            faceLoc = np.array(faceLoc)
            faceLoc = faceLoc / 0.25
            faceLoc=faceLoc.astype(int)
            #y1,x2,y2,x1 = faceLoc # in the other code we risize the face
            #y1, x2, y2, x1 = y1*4,x2*4,y2*4,x1*4
            y1, x2, y2, x1 = faceLoc[0], faceLoc[1], faceLoc[2], faceLoc[3]
         
            cv2.rectangle(img,(x1,y1),(x2,y2),(0,255,0),2)
            cv2.rectangle(img,(x1,y2-35),(x2,y2),(0,255,0),cv2.FILLED)
            cv2.putText(img,name,(x1+6,y2-6),cv2.FONT_HERSHEY_COMPLEX,1,(255,255,255),2)
            print("Open the Doooooooooooooooooooooooooooooooooooooooooooooooooooooor")
 
    cv2.imshow('Webcam',img)
    key = cv2.waitKey(1)
    if key == 27:
        break
cap.release()
cv2.destroyAllWindows()

matches [True, False, True, True]
[0.40323817 0.85257616 0.5643085  0.56188613]
ESLAM ZOGHLA
Open the Doooooooooooooooooooooooooooooooooooooooooooooooooooooor
matches [True, False, True, True]
[0.40808666 0.8085605  0.55144683 0.50499996]
ESLAM ZOGHLA
Open the Doooooooooooooooooooooooooooooooooooooooooooooooooooooor
matches [True, False, True, True]
[0.42315089 0.84755843 0.57656626 0.50653596]
ESLAM ZOGHLA
Open the Doooooooooooooooooooooooooooooooooooooooooooooooooooooor
matches [True, False, True, True]
[0.44293085 0.88361647 0.5646287  0.51501482]
ESLAM ZOGHLA
Open the Doooooooooooooooooooooooooooooooooooooooooooooooooooooor
matches [True, False, True, True]
[0.40830737 0.83741244 0.5545833  0.51404529]
ESLAM ZOGHLA
Open the Doooooooooooooooooooooooooooooooooooooooooooooooooooooor
matches [True, False, False, True]
[0.41852989 0.82837984 0.61038908 0.534176  ]
ESLAM ZOGHLA
Open the Doooooooooooooooooooooooooooooooooooooooooooooooooooooor
matches [True, False, False, True]
[0.4049942

In [15]:
from flask import Flask, render_template

In [26]:
myApp = Flask(__name__)

@myApp.route('/')
def index():
    return render_template('index.html')

@myApp.route('/Eslam')
def name():
    return 'Hello, Eslam'

if __name__ == '__main__':
    myApp.run()

 * Serving Flask app '__main__' (lazy loading)
 * Environment: production
   Use a production WSGI server instead.
 * Debug mode: off


 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [07/May/2024 02:02:14] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [07/May/2024 02:02:19] "GET /[object%20ArrayBuffer] HTTP/1.1" 404 -


In [25]:
import cv2
import numpy as np
import face_recognition
import os


# Resize the image
frame_resizing = 0.25
imgS = cv2.resize(img, (0, 0), fx=frame_resizing, fy=frame_resizing)

# Convert image to RGB (face_recognition library requires RGB format)
imgS = cv2.cvtColor(imgS, cv2.COLOR_BGR2RGB)

# Detect faces in the image
facesCurFrame = face_recognition.face_locations(imgS)
encodesCurFrame = face_recognition.face_encodings(imgS, facesCurFrame)

# Loop through each detected face
for encodeFace, faceLoc in zip(encodesCurFrame, facesCurFrame):
    matches = face_recognition.compare_faces(encodeListKnown, encodeFace)
    print('matches', matches)
    faceDis = face_recognition.face_distance(encodeListKnown, encodeFace)
    print(faceDis)
    matchIndex = np.argmin(faceDis)
    if matches[matchIndex]:
        name = classNames[matchIndex].upper()
        print(name)

        faceLoc = np.array(faceLoc)
        faceLoc = faceLoc / 0.25
        faceLoc = faceLoc.astype(int)
        y1, x2, y2, x1 = faceLoc[0], faceLoc[1], faceLoc[2], faceLoc[3]

        cv2.rectangle(img, (x1, y1), (x2, y2), (0, 255, 0), 2)
        cv2.rectangle(img, (x1, y2-35), (x2, y2), (0, 255, 0), cv2.FILLED)
        cv2.putText(img, name, (x1+6, y2-6), cv2.FONT_HERSHEY_COMPLEX, 1, (255, 255, 255), 2)
        print("Open the Doooooooooooooooooooooooooooooooooooooooooooooooooooooor")


matches [True, False, False, True]
[0.58487213 0.78497533 0.63554488 0.4599531 ]
YAHYA HAMZA
Open the Doooooooooooooooooooooooooooooooooooooooooooooooooooooor
